name: 'Eclipse plug-in deployment to server'
description: 'Provides the facility to deploy versioned Maven-built Eclipse plug-ins to an ssh host.'
inputs:
  remote-host:
    description: 'Remote host'
    required: true
  remote-user:
    description: 'Remote user'
    required: true
  remote-root:
    description: 'Remote root folder'
    required: true
  remote-baseurl:
    description: 'Remote url basis'
    required: true
  remote-relative-path:
    description: 'Remote path for deployment relative to root'
    required: true
  maven-target:
    description: 'Name of maven target folder'
    required: true
  sym-link-name:
    description: 'Override name of symlink on target'
    required: false
    default: 'update'
outputs:
  version:
    description: 'Version of the plug-in'
    value: ${{ steps.get-version.outputs.version }}
  dest:
    description: 'Destination'
    value: ${{ steps.upload.outputs.dest }}
runs:
  using: "composite"
  steps:
    - id: get-version
      run: ${GITHUB_ACTION_PATH}/get_version.sh ${{ inputs.maven-target }}
      shell: bash

    - id: upload
      run: >
          ${GITHUB_ACTION_PATH}/upload.sh
          ${{ inputs.maven-target }}
          "${{ inputs.sym-link-name }}"
          "${{ inputs.email }}"
          "${{ steps.get-version.outputs.version }}"
          ${{ inputs.remote-user }}@${{ inputs.remote-host }}
          ${{ inputs.remote-root }}/${{ inputs.relative-path }}
      shell: bash
